google_analytics_id: G-X0BJ20T7XR

hero_image: assets/img/bg.jpg
hero_position: center center

theme:
  # text_color: '#404040'
  primary_color: '#5F8575'
  #secondary_color: '#C46931'
  secondary_color: '#89ab9c'
  # accent_color: '#afa63d'
  background_color: '#ffff'

people:
  families_header: Novomanželé
  families_text: Tak to jsme my, s většinou se navzájem známe a se zbytkem se rádi doseznámíme v náš velký den.
  kids_header: Svědci 
  kids_text: Kačka si vybrala za svou svědkyni Terku. S tou jsou kamarádky už od 4 let, kdy spolu chodily celé dětství do Kyjovánku. <br>Rado si vybral za svojho svedka Vaška, s ktorým sa stretol až po ukončení bakalárskeho štúdia, ale odvtedy to spolu ťahajú v práci aj v živote.
  wedding_party_header: Organizace svatby
  wedding_party_text: Pokud máte jakékoli dotazy týkající se organizace, obraťte se na Janulu, která vám je ráda zodpoví.
  # his_side: null
  # her_side: False