google_analytics_id: G-X0BJ20T7XR

hero_image: assets/img/bg.jpg
hero_position: center center

theme:
  # text_color: '#404040'
  primary_color: '#5F8575'
  #secondary_color: '#C46931'
  secondary_color: '#89ab9c'
  # accent_color: '#afa63d'
  background_color: '#ffff'

people:
  families_header: Novomanželé
  families_text: O nas ....
  kids_header: Svědci 
  kids_text: Naši svedkovia su ....
  wedding_party_header: Wedding manager
  wedding_party_text: Ak mate akekolvek otazky k organizacii kontaktujte janulu12...
  # his_side: null
  # her_side: False